name: Deploy UI

on:
  push:
    branches:
      - caddy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to OCI VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ~/deploy-ui.sh
